modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
credits="https://freesound.org/people/RutgerMuller/sounds/51044/ Recycler sound"
[[mods]]
    modId="piscary"
    version="${file.jarVersion}"
    displayName="Piscary"
    authors="joshiejack"
    description='''Fish, Fish Trap, Hatchery, Recycler...'''
[[dependencies.piscary]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.piscary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.piscary]]
    modId="penguinlib"
    mandatory=true
    versionRange="[0.3.0,)"
    ordering="NONE"
    side="BOTH"